/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://rskwmghvcfdcjarz2ia5coj3xa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zghrnbmewjal7lnqv7mvu6bcty",
    "aws_cognito_identity_pool_id": "us-east-2:bb02700d-7a92-4db1-b2a2-ef5d0ae5e04a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_msKLp1Tm8",
    "aws_user_pools_web_client_id": "350vm9gfqbl6tg3p4e12l3k1cf",
    "oauth": {
        "domain": "evryday-beta.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid"
        ],
        "redirectSignIn": "com.evryday://",
        "redirectSignOut": "com.evryday://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
